name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1  # ← ПРАВИЛЬНЫЙ ACTION!
        with:
          host: course.prafdin.ru
          port: 2200
          username: kali
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u derasoft004 --password-stdin
            
            cd ~/Desktop/catty-reminders-app
            echo "DATABASE_URL=postgresql://catty:cattypass@db:5432/cattydb" > .env
            echo "DEBUG=false" >> .env
            
            docker pull ghcr.io/derasoft004/catty-app-test:latest
            
            docker-compose down || true
            docker-compose up -d
            
            
