name: CI Pipeline

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: unit tests
        run: pip install pytest
      
      - name: Run unit tests
      - name: Run unit tests only
        run: python -m pytest tests/my_unit_test.py -v
      
